### ISSUE TITLE
Preheat constant calculation overflows

### ISSUE THREAD

**Issue by stellanl** [tobiasschuerg/MH-Z-CO2-Sensors#10]
On ATmega an int is only 16 bits, so the preheating constants get bad values ( -16608), and the preheat check does not work as intended. I had to change the declarations like this to make it work:

const unsigned long MHZ14A_PREHEATING_TIME = 3 * 60 * 1000ul;

**Comment by tobiasschuerg** [comment]
Thanks for the note.
