### ISSUE TITLE
16bit integer constant on Arduino Uno

### ISSUE THREAD

**Issue by jiri-janacek** [tobiasschuerg/MH-Z-CO2-Sensors#23]
I have changed type of the constants to long, otherwise Arduino Uno waits forever

const long MHZ14A_PREHEATING_TIME = 3 * 60 * 1000L;
const long MHZ19B_PREHEATING_TIME = 3 * 60 * 1000L;

const long MHZ14A_RESPONSE_TIME = 60 * 1000L;
const long MHZ19B_RESPONSE_TIME = 120 * 1000L;

**Comment by tobiasschuerg** [comment]
This issue seems outdated:
https://github.com/tobiasschuerg/MH-Z-CO2-Sensors/blob/7be7cf0f22e8c3bcd9c7357b2a1ef2f70d8d0c8a/MHZ.cpp#L14-L18
