### ISSUE TITLE
Other MH-Z libraries

### ISSUE THREAD

**Issue by MPParsley** [tobiasschuerg/MH-Z-CO2-Sensors#28]
Thank you for this library.

How does this library differ from https://github.com/WifWaf/MH-Z19?

**Comment by tobiasschuerg** [comment]
This one was there first ;-)

Actually I don't know but I expect they both work fine and for basic usage and it does not matter which one you choose.

Besides that WifWaf seems to have implemented [more Commands](https://github.com/WifWaf/MH-Z19#commands) but is therfore twice as large. 

Also the licences differ (MIT vs LGPL).
