### ISSUE TITLE
Pin configuration for Wemos D1 mini

### ISSUE THREAD

**Issue by Boerny41** [tobiasschuerg/MH-Z-CO2-Sensors#30]
Hi,

all I am getting as output is 

17:45:17.352 -> ..................................
17:48:07.348 -> 
17:48:07.348 -> ----- Time from start: 180 s
17:48:08.567 -> PPMuart: n/a

I have tried every combination of pins I could think of and tried to change them. Besides that the code is unchanged. Controller is a D1 mini.

Is there anything I am doing wrong?

**Comment by tobiasschuerg** [comment]
> Is there anything I am doing wrong?

That's not enough information. Actually you are just saying "it's not working" ...

I once also used a Wemos and from a look at some quite old code, I can tell that I used pins `RX_PIN 13` amd ` TX_PIN 15` - but if you really tried *every combination of pins I could think of*  then there will be some other issue. 

Maybe the sensor is broken?

**Comment by tobiasschuerg** [comment]
Maybe check out some Blog posts from other people about the correct wireing.
For example https://esp8266-server.de/MQTT/CO2-Sensor.html

**Comment by Boerny41** [comment]
I was unable to figure out what was wrong but I still guess something with the pinout. In the end I used esp-easy.
