### ISSUE TITLE
Support for MH-Z14B

### ISSUE THREAD

**Issue by il0vew33d** [tobiasschuerg/MH-Z-CO2-Sensors#35]
could you please add support for the MH-Z14B sensor?
It has a shorter preheat time (30s).
https://www.winsen-sensor.com/d/files/infrared-gas-sensor/mh-z14b-co2-manual(ver1_0).pdf

thanks a lot.

**Comment by tobiasschuerg** [comment]
@il0vew33d please check out version 1.5.0 which has support for the Z14B
