### ISSUE TITLE
Platform.io warning: Could not find the linux_x86_64 package

### ISSUE THREAD

**Issue by ben700** [tobiasschuerg/MH-Z-CO2-Sensors#42]
Using platformio if I include the library using URL **https://github.com/tobiasschuerg/MH-Z-CO2-Sensors/archive/refs/tags/1.4.0.zip** all works and I don't get any warnings or errors 

If I include using  **tobiasschuerg/MH-Z-CO2-Sensors @ ^1.4.0** then I get the warning shown below

Library Manager: Installing tobiasschuerg/MH-Z-CO2-Sensors @ ^1.4.0
Warning! Could not find the package with 'tobiasschuerg/MH-Z-CO2-Sensors @ ^1.4.0' requirements for your system 'linux_x86_64'

It's only a warning, I just wanted to give you feedback 

Warm Regards

Ben

**Comment by tobiasschuerg** [comment]
That's probably more a platform.io issue...
