### ISSUE TITLE
Version 1.4.1 isn't visible in Platform.IO registry

### ISSUE THREAD

**Issue by SNMetamorph** [tobiasschuerg/MH-Z-CO2-Sensors#45]
That's just because you missed to create tag for 1.4.1 release

**Comment by tobiasschuerg** [comment]
Thanks for the note. 
Just created a release for `1.4.1` and the new `1.5.0`:
https://github.com/tobiasschuerg/MH-Z-CO2-Sensors/releases/tag/1.5.0
Those versions should appear in the registires soon.

**Comment by thehans** [comment]
From what I have read PlatformIO registry should update existing libraries every 24hrs.  

It seems this has not occurred (latest and only version in PlatformIO registry is 1.4.0 ), so I searched for why this would happen, and found this topic: https://community.platformio.org/t/library-is-not-updating-in-platformio-registry/33198

Where it sounds like the solution is that you must run `pio pkg publish`
https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html

Has this been done?  I think only repository owner has authorization to do so.

**Comment by tobiasschuerg** [comment]
@thehans seems like the crawler found it automatically:
https://registry.platformio.org/libraries/tobiasschuerg/MH-Z%20CO2%20Sensors
